/title:        Vinit Kumar
tagline:      'Who needs a tag!'
description:  'Blog about Web & Programming'
url:          http://vinitkumar.me
version:      1.1.0
author:
  name:       'Vinit Kumar'
  email:      'vinit.kumar@changer.nl'

# owner/author information
owner:
  name:           Vinit Kumar
  avatar:         <your avatar>
  email:          vinit.kumar@changer.nl
  # Social networking links used in footer. Update and remove as you like.
  twitter: vinitkme
  github: vinitkumar
  stackexchange: 458929
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  +Vinitkumarme

# Analytics and webmaster tools stuff goes here
google_analytics: UA-40854387-1
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

markdown:     kramdown
permalink:    pretty
pygments:     true
paginate:     5
